#name: Exam Notifier
#
#on:
#  schedule:
#    - cron: "*/15 * * * *"
#
#  workflow_dispatch:
#    inputs:
#      mode:
#        description: "Run mode"
#        required: true
#        default: "prod"
#        type: choice
#        options:
#          - prod
#          - test
#
#jobs:
#  run-notifier:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v4
#
#      - name: Setup Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.12"
#
#      - name: Install Dependencies
#        run: |
#          pip install -r requirements.txt
#
#      - name: Run Notifier
#        env:
#          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
#          CHAT_ID: ${{ secrets.CHAT_ID }}
#          RUN_MODE: ${{ github.event.inputs.mode || 'prod' }}
#        run: |
#          python main.py